apiVersion: v1
kind: Service
metadata:
  name: {{ include "iwx-service.fullname" . }}
  labels: {{- include "iwx-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "iwx-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
    {{- range .Values.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
    {{- end }}
