apiVersion: v1
kind: Secret
metadata:
  name: iwx-shared-secrets
  namespace: iwx
type: Opaque
stringData:
  SQL_SA_PASSWORD: "IwxStrong!Passw0rd"
  MONGO_USER: "iwx"
  MONGO_PASS: "iwx"
  RABBIT_USER: "iwx"
  RABBIT_PASS: "iwx"
  JWT_SECRET: "iwx-prod-rotate-this-secret-min-32-chars-long-please-1234"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iwx-shared-config
  namespace: iwx
data:
  RABBITMQ_HOST: "rabbitmq"
  MONGO_HOST: "mongo"
  REDIS_HOST: "redis"
  KAFKA_BOOTSTRAP: "kafka:9092"
  OLLAMA_HOST: "http://ollama:11434"
  OLLAMA_MODEL: "llama3.2:3b"
  SQL_HOST: "sqlserver"
  SQL_PORT: "1433"
